import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
    public static void main(String[] args) throws SQLException {
        String hostname = "localhost"; // 自分のものに書き換える
        String dbname = "hello_database"; // 自分のものに書き換える
        String username = "hello"; // 自分のものに書き換える
        String password = "abcdef"; // 自分のものに書き換える
        Connection conn = null;
        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection("jdbc:postgresql://" + hostname
                    + ":5432/" + dbname, username, password);
            System.out.println("接続成功");
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
}
