import java.sql.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
    public static void main(String[] args) throws SQLException {
        String hostname = "localhost"; // 自分のものに書き換える
        String dbname = "hello_database"; // 自分のものに書き換える
        String username = "hello"; // 自分のものに書き換える
        String password = "abcdef"; // 自分のものに書き換える

        try(
                Connection conn = DriverManager.getConnection("jdbc:postgresql://" + hostname
                + ":5432/" + dbname, username, password);
                Statement stmt = conn.createStatement()
                ) {

            Class.forName("org.postgresql.Driver");

            System.out.println("接続成功");

            stmt.executeUpdate("CREATE TABLE products (pid INTEGER, name VARCHAR(20), price INTEGER, PRIMARY KEY (pid))");
            System.out.println("テーブル作成");

            stmt.executeUpdate("INSERT INTO products VALUES(1, 'AAA', 100)");
            stmt.executeUpdate("INSERT INTO products VALUES(2, 'BBB', 80)");
            stmt.executeUpdate("INSERT INTO products VALUES(3, 'CCC', 220)");
            System.out.println("データ挿入");

            ResultSet rs = stmt
                    .executeQuery("SELECT * FROM products WHERE price >= 100");
            System.out.println("選択");
            while (rs.next()) {
                int pid = rs.getInt("pid");
                String name = rs.getString("name");
                int price = rs.getInt("price");
                System.out.println(pid + "\t" + name + "\t" + price);
            }
            rs.close();

            stmt.executeUpdate("DROP TABLE products");
            System.out.println("テーブル削除");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
